# Generated by Django 5.1.1 on 2024-10-10 17:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('b_form_cnic', models.CharField(max_length=13, unique=True)),
                ('rollnumber', models.CharField(editable=False, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('father_cnic', models.CharField(max_length=13, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('age', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MaxValueValidator(100)])),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
