# Generated by Django 5.1.1 on 2024-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('credit_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
