# Generated by Django 5.1.1 on 2024-10-11 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_student_registration_number_alter_student_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classs',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(max_length=20),
        ),
    ]
