# Generated by Django 5.1.1 on 2024-10-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_student_classs_alter_student_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(max_length=13),
        ),
    ]
