# Generated by Django 5.1.1 on 2024-10-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0007_alter_student_father_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
